from fastapi import APIRouter

from .routes import users, projects, videos, video_detail, comments, notifications, activity_feeds, upload, annotations, google_account_integration, youtube_oauth, folders, billing, review_links, review_workflows, ai, creator, freelancer, suggestions, community_forum, workspaces, public_workspace, project_tasks, delivery, security_audit, editor_integrations, proxy, watch_folder, ingest, clips, ugc
# , 
# analytics
# google_account_integration

api_router = APIRouter()
api_router.include_router(users.router)
api_router.include_router(workspaces.router)
api_router.include_router(public_workspace.router)
api_router.include_router(project_tasks.router)
api_router.include_router(projects.router)
api_router.include_router(review_workflows.router)
api_router.include_router(videos.router)
api_router.include_router(video_detail.router)
api_router.include_router(comments.router)
api_router.include_router(notifications.router)
api_router.include_router(activity_feeds.router)
api_router.include_router(upload.router)
api_router.include_router(annotations.router)
# api_router.include_router(analytics.router)
api_router.include_router(google_account_integration.router)
api_router.include_router(youtube_oauth.router)
api_router.include_router(folders.router)
api_router.include_router(billing.router)
api_router.include_router(review_links.auth_router)
api_router.include_router(review_links.public_router)
api_router.include_router(ai.router)
api_router.include_router(creator.router)
api_router.include_router(freelancer.router)
api_router.include_router(freelancer.public_router)
api_router.include_router(suggestions.router)
api_router.include_router(community_forum.router)
api_router.include_router(delivery.router)
api_router.include_router(delivery.public_router)
api_router.include_router(security_audit.router)
api_router.include_router(editor_integrations.router)
api_router.include_router(proxy.router)
api_router.include_router(watch_folder.router)
api_router.include_router(ingest.router)
api_router.include_router(clips.router)
api_router.include_router(ugc.router)
api_router.include_router(ugc.public_router)

